name: Deploy to GitHub Pages

on:
  push:
    branches:
      - hugo

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with: 
          token: ${{ secrets.TOKEN }}
          submodules: 'true'
      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: config1
        # 将从 content 目录中删除某些文件和目录，然后将所有 .md 文件移回 content 目录中，最后将 Home.md 文件重命名为 _index.md 文件
        run: rm -rf content/.obsidian content/cedict_ts.u8 content/Extras && mv content/*.md content/Atlas && find content/ -name "*.md" | xargs -I file  mv -f file content &&  mv content/Home.md content/_index.md 

      - name: config2
        # 列出 content 目录下所有文件和目录，找到其中所有包含字符串 title 的文件，并将其中的 title 字段格式化为 "title" 的形式
        run: "ls content/ && grep -lr --null 'title' content/* | xargs -0 sed -i -E -r 's/title: (.*)/title: \"\\1\"/g'"

      - name: config3 
        run: rm -rf content/*.md-E

      - name: Build Link Index
        uses: jackyzha0/hugo-obsidian@v2.20
        with:
          index: true
          input: content
          output: assets/indices
          root: .

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.96.0'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./public
          publish_branch: master  # deploying branch
          cname: guanpj.github.io
